on:
  push:
    branches:
      - maste




jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: 'Printing folder contents'
        run: ls

      - uses: actions/checkout@v3
     
      - name: 'Printing folder contents'
        run: ls