on:
  push:
    branches:
      - maste




jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: 'Testing Github action'
        run: pwd 

      - name: 'Testing Printing'
        run: echo Ahmed 
