on:
  push:
    branches:
      - maste




jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: 'Printing folder contents'
        run: ls

      - uses: actions/checkout@v3
     
      - name: 'Login to Docker hub'
        run: docker login --username os2023 --password dckr_pat_7oG0lYZTwJRvt84Swg3F7ODFTVI